// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagMQc_urYNz56ZuB2BsX676-kafKUKk0',
    appId: '1:620286182402:web:253c9888cf9bdf01c9131b',
    messagingSenderId: '620286182402',
    projectId: 'fir-8995d',
    authDomain: 'fir-8995d.firebaseapp.com',
    storageBucket: 'fir-8995d.appspot.com',
    measurementId: 'G-9037YMY0G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAynMElq_wHif3rJCOzjbFD18NIbLwwRVQ',
    appId: '1:620286182402:android:a3bc202910999c9ac9131b',
    messagingSenderId: '620286182402',
    projectId: 'fir-8995d',
    storageBucket: 'fir-8995d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK6JEFiBhpjFiQ5PBQxz4iVesi7ust8lY',
    appId: '1:620286182402:ios:7a35670779e883ccc9131b',
    messagingSenderId: '620286182402',
    projectId: 'fir-8995d',
    storageBucket: 'fir-8995d.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK6JEFiBhpjFiQ5PBQxz4iVesi7ust8lY',
    appId: '1:620286182402:ios:7a35670779e883ccc9131b',
    messagingSenderId: '620286182402',
    projectId: 'fir-8995d',
    storageBucket: 'fir-8995d.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
